# Generated by Django 3.2.5 on 2021-07-10 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the exercise', max_length=1024)),
                ('min_range_amount', models.IntegerField(default=2, help_text='Minimum of the range where a random amount for this exercise will be picked out of')),
                ('max_range_amount', models.IntegerField(default=5, help_text='Maximum of the range where a random amount for this exercise will be picked out of')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the player', max_length=1024)),
                ('multiplier', models.IntegerField(default=1, help_text='How many chances per roll a player gets for losing')),
            ],
        ),
    ]
